version: '3.8'

services:
  frontend:
    build: ./frontend/front-ToDo
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/front-ToDo:/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/api-ToDo  # Caminho corrigido para build
    ports:
      - "8000:8001"  # Mapeia a porta 8000 do contêiner para a porta 8000 do host
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh mysql:3306 -- php artisan migrate --force && php-fpm"
      php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql  # Configuração básica para aguardar o MySQL iniciar

volumes:
  mysql_data:

