version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/front-ToDo
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/front-ToDo:/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend/api-ToDo
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: database_name
      DB_USERNAME: user_name
      DB_PASSWORD: user_password
    command: >
      sh -c "sleep 10 && php artisan migrate --force && php-fpm"

volumes:
  mysql_data:
