version: '3'

services:
  frontend:
    build: ./frontend/front-ToDo
    ports:
      - '8080:80'
    volumes:
      - ./frontend/front-ToDo:/app
    networks:
      - todo-network

  backend:
    build: ./backend/api-ToDo
    ports:
      - '3000:3000'
    volumes:
      - ./backend/api-ToDo:/app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - todo-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
